feat: implement the delete handler and its logic in the tree service
green-ecolution/green-ecolution-backend pull request #102
Opened 2024-10-05 20:18 UTC by Mohammad96Assaf

2024-10-06 14:28 UTC, choffmann requested changes
:1st_place_medal:

2024-10-06 14:28 UTC, choffmann commented on internal/server/http/handler/v1/tree/handler.go
>  // @Param			Authorization	header	string	true	"Insert your access token"	default(Bearer <Add access token here>)
Please add the id to swagger

```suggestion
// @Router			/v1/tree/{tree_id} [delete]
// @Param			treecluster_id	query	string	false	"Tree Cluster ID"
// @Param			Authorization	header	string	true	"Insert your access token"	default(Bearer <Add access token here>)
```

2024-10-08 20:03 UTC, Mohammad96Assaf commented on internal/server/http/handler/v1/tree/handler.go
>  // @Param			Authorization	header	string	true	"Insert your access token"	default(Bearer <Add access token here>)
Why treecluster_id, you mean tree_id ?

2024-10-09 15:15 UTC, choffmann approved these changes
Please change query to path, then you can merge the pr

2024-10-09 15:15 UTC, choffmann commented on internal/server/http/handler/v1/tree/handler.go
> +// @Param			tree_id			query	string	false	"Tree ID"
It's not a query parameter, it's a path parameter.

```suggestion
// @Param			tree_id			path	string	false	"Tree ID"
```

2024-10-09 19:45 UTC, merged