Feature/flowerbed repository tests
green-ecolution/green-ecolution-backend pull request #205
Opened 2024-11-05 18:07 UTC by doriengr

2024-11-15 13:05 UTC, Zoka-tech commented on internal/storage/postgres/flowerbed/get_test.go
> +var allTestFlowerbeds = []*testFlowerbeds{
Maybe seperate the "fake" Flowerbed Data into its own file to have this a bit more organized?

2024-11-15 17:02 UTC, choffmann requested changes
:fire:

2024-11-16 08:43 UTC, doriengr commented on internal/storage/postgres/flowerbed/flowerbed.go
> +	}
Perhaps the implementation is not correct, but the reason for this check are the tests in which a non-existent id is overgiven and it should return an error. Before the implementation the return value was always nil.  

I based the structure on the Delete tree cluster.
https://github.com/green-ecolution/green-ecolution-backend/blob/e5cd1d9a2b3a62e75eb4bdff98ae9d66217b0f5f/internal/storage/postgres/treecluster/treecluster.go#L125

2024-11-16 08:45 UTC, doriengr commented on internal/storage/postgres/flowerbed/flowerbed.go
> +	}
What is the correct way?

2024-11-16 19:18 UTC, choffmann approved these changes
:+1:

2024-11-16 19:36 UTC, merged