Feature/add sensor data to respons
green-ecolution/green-ecolution-backend pull request #294
Opened 2024-12-23 18:43 UTC by doriengr

2024-12-24 01:11 UTC, Mohammad96Assaf requested changes
The changes inside **handleMqttMessage** are causing an issue, and the data from TTN cannot be converted correctly.
Please fix the problem and verify if the data is still read from TTN and stored in the database correctly.

2024-12-24 06:47 UTC, doriengr commented
> The changes inside **handleMqttMessage** are causing an issue, and the data from TTN cannot be converted correctly. Please fix the problem and verify if the data is still read from TTN and stored in the database correctly.

Csn you show me how to test it?

2024-12-28 08:17 UTC, doriengr commented
> The changes inside **handleMqttMessage** are causing an issue, and the data from TTN cannot be converted correctly. Please fix the problem and verify if the data is still read from TTN and stored in the database correctly.

Is fixed 👍

2024-12-29 15:41 UTC, Mohammad96Assaf requested changes

2024-12-29 15:41 UTC, Mohammad96Assaf commented on internal/storage/postgres/sensor/entities/mqtt_payload.go
> +	Longitude   float64     `json:"longitude"`
Why are latitude and longitude being added here? These values are already saved once directly as sensor attributes, so there’s no need to include them again in the sensor data, every time the data is stored.

We’ve previously discussed the structure of sensor data in #233.

2024-12-29 16:13 UTC, Mohammad96Assaf approved these changes

2024-12-29 16:30 UTC, merged